version: '3.9'

services: 
  spring: 
    container_name: springapp
    image: francescoxx/springboot
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      - PG_DATABASE=example
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 